Print the exit code when error occurs

diff --git a/retry b/retry
--- a/retry
+++ b/retry
@@ -13,5 +13,8 @@ while [ $SUCCESS == false ]; do
     bash -c "$*"
     if [ $? == 0 ]; then
         SUCCESS=true
+    else
+        # Print the exit code when error occurs
+        echo $?
     fi
 done
